### PR TITLE
Fix #1: Cant detect Windows Server 2008

### PR DESCRIPTION
**Pull request by jacargentina**
The API is changed just by a new optional bool parameter `fullName`. When invoked like this:

```js
const os = require('os');
const winRelease = require('win-release');

winRelease(os.release(), true);
//=> 'Windows Server 2008 R2'

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm not really interested in an option for this or having to maintain a name for every build release. I am open to adding a special case detection for Windows Server 2008 though.

**Comment by silverwind** [comment]
I too think this is not the right approach, it should only return a single version, and probably without the option.

Server 2008, 2012 and 2016 need an additional check to tell them apart from the non-server versions and for the others, you can get away by just looking at the first two digits in the version.

**Comment by jacargentina** [comment]
I can have my own fork if needed, at least i did sonething!

**Comment by silverwind** [comment]
Working on this.

**Comment by silverwind** [comment]
https://github.com/sindresorhus/win-release/pull/7

**Comment by sindresorhus** [comment]
Closing in favor of #7.

**Pull request closed without merging**
