### PR TITLE
 Reversed order checking for WMIC or Powershell

### LINKED ISSUE #16: Causing aroung 800ms delay between version 3.2.0 and 3.3.0
The scenario -
- I have an Azure NodeJS function
  - Azure function has a dependency on CosmosDB NodeJS package
  - [Azure Cosmos DB NodeJS package](https://github.com/Azure/azure-sdk-for-js/blob/2e3cf69ad5363e9c36eb02e7035b5176515d1698/sdk/cosmosdb/cosmos/package.json#L89) has dependency over [os-name package](https://github.com/sindresorhus/os-name#readme)
  - os-name package has the dependency over windows-release package

I had a production system running on Cosmos NodeJS package (version 3.6.2) and recently I made some changes and tried to deploy the new code over the production. I started to see the latency of around 800ms in cosmos DB insertion call. The cosmos DB package version was the same so the issue was in one of the dependency. I manually checked each and every package on which Cosmos DB and it's dependencies are dependent on (trust I checked a lot of code and releases) and could drill down to the specific version which is causing the issue.

The Windows-release package version 3.3.0 is causing the Cosmos to delay the result by 800ms to 1000ms. While with Windows-release package version 3.2.0 Cosmos DB doesn't show this much of delay. (Given that everything in the system was constant and every other factor which might impact the results had been eliminated).

When comparing Windows-release 3.3.0 with Windows-release 3.2.0, I found that the only part in the code that has been changed is the below snippet

https://github.com/sindresorhus/windows-release/blob/39b78e784527b9202968bf518640283f57541fe1/index.js#L36-L40

Basically Windows-release moved from `wmic` to use `PowerShell` by default [in this commit](https://github.com/sindresorhus/windows-release/commit/75916af29c166a9c2cd778b61fe52738614b8259) and in case `PowerShell` fails, fallback to `wmic` and I suspect that due to this fallback and changing default from `wmic` to `PowerShell` is causing the delay.

### LINKED ISSUE #17: Hangs when running v3.3 on Windows Server 2012 R2
When I try a to run `windows-release` on our build machine it simply hangs and never returns anything.

Running the powershell command directly as the same user it gives me:
```
Microsoft Windows Server 2012 R2 Standard
```
When I roll back to version 3.2 I don't get any issue as it isn't using the powershell command.

Any ideas what might be causing the hang?

### PR DESCRIPTION
**Pull request by landsfiskalen**
Ok, I reversed the order checking for WMIC or Powershell. Should be more compatible to 3.2 now.

Fixes #17
Fixes #16

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by landsfiskalen** [comment]
Man, this Git stuff is hard. I'm completely new to this, but I think I've managed to resolve it now?

**Comment by landsfiskalen** [comment]
Gaaah! Managed to close the pull request.

**Comment by sindresorhus** [comment]
Tip: You should never to PRs from `master` branch.

**Pull request merged**
